"""SemRank-QSQ external reranking baseline."""

from .cache import SemRankCache
from .classifier import (
    OfficialSemRankTopicClassifier,
    TopicClassifier,
    load_official_labels,
)
from .encoder import (
    CachedConceptEncoder,
    ConceptEncoder,
    EmbeddingProviderConceptEncoder,
    Specter2MeanPoolEncoder,
)
from .models import (
    AuxiliaryPaper,
    PaperConceptProfile,
    QueryConceptProfile,
    SEMRANK_CONCEPT_NORMALIZATION_VERSION,
    SEMRANK_FORMULA_ID,
    SEMRANK_IMPLEMENTATION_VERSION,
    SEMRANK_CLASSIFIER_ONLY_PAPER_PROMPT_VERSION,
    SEMRANK_CLASSIFIER_ONLY_TOPIC_PIPELINE_VERSION,
    SEMRANK_METHOD,
    SEMRANK_METHOD_DISPLAY_NAME,
    SEMRANK_PAPER_CONCEPT_MODE_CLASSIFIER_ONLY,
    SEMRANK_PAPER_CONCEPT_MODE_FULL,
    SEMRANK_PAPER_PROMPT_VERSION,
    SEMRANK_PAPER_TEXT_PROFILE_IDENTITY_VERSION,
    SEMRANK_QUERY_PROMPT_VERSION,
    SEMRANK_QUERY_TEXT_PROFILE_IDENTITY_VERSION,
    SEMRANK_TOPIC_PIPELINE_VERSION,
    SEMRANK_ZSCORE_EPS,
    SemRankConfig,
    SemRankEventProfile,
    TopicCandidate,
    normalize_concept,
    paper_text_profile_identity,
    query_text_profile_identity,
    semrank_paper_prompt_version,
    semrank_topic_pipeline_version,
    stable_hash,
    stable_unique,
)
from .paper_concepts import (
    PaperConceptService,
    SemRankCacheMissError,
)
from .prompts import SemRankLLMClient
from .query_profile import DateValidInitialRetriever, QueryProfileBuilder
from .reranker import (
    SemRankQSQReranker,
    base_semantic_scores,
    mean_max_concept_cosine,
    population_zscore,
    semrank_scores,
)
from .retrieval import ScholarGymDateValidRetriever

__all__ = [
    "AuxiliaryPaper",
    "CachedConceptEncoder",
    "ConceptEncoder",
    "DateValidInitialRetriever",
    "EmbeddingProviderConceptEncoder",
    "OfficialSemRankTopicClassifier",
    "PaperConceptProfile",
    "PaperConceptService",
    "QueryConceptProfile",
    "QueryProfileBuilder",
    "SEMRANK_CONCEPT_NORMALIZATION_VERSION",
    "SEMRANK_FORMULA_ID",
    "SEMRANK_IMPLEMENTATION_VERSION",
    "SEMRANK_CLASSIFIER_ONLY_PAPER_PROMPT_VERSION",
    "SEMRANK_CLASSIFIER_ONLY_TOPIC_PIPELINE_VERSION",
    "SEMRANK_METHOD",
    "SEMRANK_METHOD_DISPLAY_NAME",
    "SEMRANK_PAPER_CONCEPT_MODE_CLASSIFIER_ONLY",
    "SEMRANK_PAPER_CONCEPT_MODE_FULL",
    "SEMRANK_PAPER_PROMPT_VERSION",
    "SEMRANK_PAPER_TEXT_PROFILE_IDENTITY_VERSION",
    "SEMRANK_QUERY_PROMPT_VERSION",
    "SEMRANK_QUERY_TEXT_PROFILE_IDENTITY_VERSION",
    "SEMRANK_TOPIC_PIPELINE_VERSION",
    "SEMRANK_ZSCORE_EPS",
    "ScholarGymDateValidRetriever",
    "SemRankCache",
    "SemRankCacheMissError",
    "SemRankConfig",
    "SemRankEventProfile",
    "SemRankLLMClient",
    "SemRankQSQReranker",
    "Specter2MeanPoolEncoder",
    "TopicCandidate",
    "TopicClassifier",
    "base_semantic_scores",
    "load_official_labels",
    "mean_max_concept_cosine",
    "normalize_concept",
    "paper_text_profile_identity",
    "population_zscore",
    "semrank_scores",
    "semrank_paper_prompt_version",
    "semrank_topic_pipeline_version",
    "query_text_profile_identity",
    "stable_hash",
    "stable_unique",
]
